### ISSUE TITLE
Rust View not showing

### ISSUE THREAD

**Issue by lonestarr** [sourcegear/rust-vs-extension#16]
Hi and congrats for this VS extension.

Double-clicking on "Rust View" just empty the view, with no way of switching back (the view remains empty, until I close/reopen the folder).

I've just used the template to create a hello world rust sample...

<details><summary>My VS infos</summary>
Microsoft Visual Studio Community 2022
Version 17.8.3
VisualStudio.17.Release/17.8.3+34330.188
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA973
Microsoft Visual C++ 2022

Azure App Service Tools v3.0.0   17.8.358.6298
Azure App Service Tools v3.0.0

C# Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Sourcegear Rust   1.2
Rust integration for Visual Studio, including rust-analyzer

Visual Basic Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
</details>

**Comment by ericsink** [comment]
That's unfortunate.  We'll see if we can reproduce the problem here.

**Comment by ericsink** [comment]
Sorry for the delay, but I think we've got this fixed.  A new release of the extension is now available.  Thanks!
