### ISSUE TITLE
support the CARGO_TARGET_DIR environment variable

### ISSUE THREAD

**Issue by fdncred** [sourcegear/rust-vs-extension#2]
First of all, thank you for this amazing piece of software!

It would be nice if the extension would recognize the `CARGO_TARGET_DIR` environment variable and use that path for debugging.

**Comment by ericsink** [comment]
> It would be nice if the extension would recognize the CARGO_TARGET_DIR environment variable and use that path for debugging.

Agreed.

**Comment by ericsink** [comment]
I'm just curious how you use `CARGO_TARGET_DIR`.  Is it always set?  Or do you have some kind of script that sets it for the invocation of `cargo`?

I suspect we will need to not merely recognize this environment variable, but also provide a setting to set its value.

**Comment by ericsink** [comment]
I *think* preview 0.6 should work better with respect to this issue.  We get paths for build output from `cargo metadata`, which respects `CARGO_TARGET_DIR`.  Let me know how it goes?

**Comment by fdncred** [comment]
seems to be working. thanks!
