### ISSUE TITLE
commenting / uncommenting

### ISSUE THREAD

**Issue by fdncred** [sourcegear/rust-vs-extension#4]
I can't seem to get my comment / uncomment buttons to enable. Maybe it's not supported yet?
![image](https://user-images.githubusercontent.com/343840/183146794-c529447c-ca3c-42d3-b3be-5245b7fd548b.png)

**Comment by ericsink** [comment]
Good one.  Hadn't noticed that yet.  We need to investigate.

**Comment by ericsink** [comment]
This has been implemented and should be included in the next release.

**Comment by ericsink** [comment]
This feature should be working in preview 0.6.

**Comment by fdncred** [comment]
looks good, thanks.
