### ISSUE TITLE
installing the latest version problems

### ISSUE THREAD

**Issue by fdncred** [sourcegear/rust-vs-extension#9]
I'm getting this error when going through the normal visual studio extension installation upgrade/update.
![image](https://user-images.githubusercontent.com/343840/196724085-e73a7f13-738c-409b-8ddc-07a8bfd184af.png)

I'm not sure if this means it succeeded or failed. Is there a version check somewhere?

**Comment by fdncred** [comment]
Nope, it didn't install the upgrade. I had to uninstall it. Search for `SourceGear Rust` again and install it in order to get the latest version.

**Comment by ericsink** [comment]
I suspect that means it failed.  The version number of the currently installed extension is shown in Manage Extensions, so you should be able to tell there whether you have 0.5 or 0.6.

It's possible that 0.5 cannot seamlessly update to 0.6.  The 0.5 release required admin privileges to install, but 0.6 does not.

I suggest manually removing 0.5 and then try installing the new version.
